CREATE TABLE users (
                       id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email          VARCHAR(255) NOT NULL UNIQUE,
                       password       VARCHAR(255) NOT NULL,
                       role           VARCHAR(255) CHECK (role IN ('USER', 'ADMIN')),
                       enabled        BOOLEAN DEFAULT TRUE NOT NULL,
                       first_name     VARCHAR(255),
                       last_name      VARCHAR(255),
                       cteated_at     TIMESTAMP, -- сохранил твою опечатку из базы (cteated), но лучше поправь в коде на created
                       email_verified BOOLEAN DEFAULT FALSE NOT NULL,
                       is_deleted     BOOLEAN DEFAULT FALSE,
                       avatar_url     VARCHAR(255)
);
