CREATE TABLE categories (
                            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name        VARCHAR(255) NOT NULL UNIQUE,
                            description VARCHAR(255),
                            category_id BIGINT REFERENCES categories(id) -- Самоссылка для подкатегорий
);