CREATE TABLE books (
                       id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title          VARCHAR(255) NOT NULL,
                       author         VARCHAR(255) NOT NULL,
                       description    VARCHAR(1000),
                       cover_url      VARCHAR(255),
                       location       VARCHAR(255) NOT NULL,
                       status         VARCHAR(255) CHECK (status IN ('AVAILABLE', 'RESERVED', 'TAKEN', 'RETURNED')),
                       active         BOOLEAN NOT NULL DEFAULT TRUE, -- Soft-delete indicator
                       deleted        BOOLEAN NOT NULL DEFAULT FALSE,
                       created_at     TIMESTAMP(6) NOT NULL,
                       category_id    BIGINT NOT NULL REFERENCES categories(id),
                       average_rating DOUBLE PRECISION DEFAULT 0.0,
                       review_count   INTEGER DEFAULT 0
);