CREATE TABLE confirmation_token (
                                    id         BIGSERIAL PRIMARY KEY,
                                    token      VARCHAR(255) NOT NULL,
                                    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                    expires_at TIMESTAMP NOT NULL
);

CREATE TABLE email_confirmation_tokens (
                                           id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           token      VARCHAR(255) NOT NULL UNIQUE,
                                           user_id    BIGINT NOT NULL UNIQUE REFERENCES users(id),
                                           expires_at TIMESTAMP(6) NOT NULL,
                                           used       BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE email_verification_token (
                                          id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          token      VARCHAR(255) NOT NULL UNIQUE,
                                          user_id    BIGINT NOT NULL UNIQUE REFERENCES users(id),
                                          expires_at TIMESTAMP(6) NOT NULL
);