CREATE TABLE reservation (
                             id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             book_id     BIGINT NOT NULL REFERENCES books(id),
                             user_id     BIGINT NOT NULL REFERENCES users(id),
                             status      VARCHAR(255) CHECK (status IN ('ACTIVE', 'COMPLETED', 'EXPIRED', 'CANCELLED', 'RETURNED')),
                             reserved_at TIMESTAMP(6),
                             taken_at    TIMESTAMP(6),
                             returned_at TIMESTAMP(6),
                             expires_at  TIMESTAMP(6)
);

CREATE TABLE book_history (
                              id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              book_id    BIGINT NOT NULL REFERENCES books(id),
                              user_id    BIGINT REFERENCES users(id),
                              event_type VARCHAR(255) NOT NULL CHECK (event_type IN ('RESERVED', 'CANCELLED', 'TAKEN', 'RETURNED', 'EXPIRED')),
                              comment    VARCHAR(255),
                              created_at TIMESTAMP(6) NOT NULL
);