CREATE TABLE notifications (
                               id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id    BIGINT REFERENCES users(id),
                               title      VARCHAR(255),
                               message    TEXT,
                               type       VARCHAR(255) CHECK (type IN ('RESERVATION_SUCCESS', 'REMINDER_TO_PICKUP', 'RESERVATION_CANCELLED', 'RETURN_REMINDER', 'OVERDUE_ALERT')),
                               is_read    BOOLEAN NOT NULL DEFAULT FALSE,
                               created_at TIMESTAMP(6)
);